# -*- coding: utf-8 -*-
"""ANOVA_виды_лечения.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1maCj_uegomP4Lchk3W2XFVGfle0FIEJp
"""

import pandas as pd
import numpy as np

df = pd.read_csv('genetherapy.csv')

df_new = pd.DataFrame()
df_new['A'] = df[df['Therapy'] == 'A']['expr'].reset_index(drop=True)
df_new['B'] = df[df['Therapy'] == 'B']['expr'].reset_index(drop=True)
df_new['C'] = df[df['Therapy'] == 'C']['expr'].reset_index(drop=True)
df_new['D'] = df[df['Therapy'] == 'D']['expr'].reset_index(drop=True)


grand_mean = round(df_new.mean().mean(), 1)
print(f'grand_mean = {grand_mean}')

sst = sum(round(((df_new.mean() - grand_mean) ** 2), 1))
print(f'sst = {sst}')

df_all = len(df_new) * df_new.columns.size - df_new.columns.size
print(f'df_all = {df_all}')

ssb = sum(round( (len(df_new)*(df_new.mean() - grand_mean) ** 2), 1) )
print(f'ssb = {ssb}')

df_bg = df_new.columns.size - 1
Ms_bg = ssb/df_bg

ssw = round(((df_new - df_new.mean())**2).sum().sum(), 1)
print(f'ssw = {ssw}')

Ms_wg = round(ssw/df_all, 2)
print(Ms_wg)

F = round(Ms_bg/Ms_wg, 3)
print(f'F = {F}')

from scipy.stats import f
import matplotlib.pyplot as plt

plt.figure(figsize=(20,8))

dfn, dfd = df_bg, df_all

x = np.linspace(0, F+1)

plt.plot(x, f.pdf(x, dfn, dfd),'r-', lw=5, alpha=0.6, label='f pdf')

plt.axvline(x=F, label='F-score')

plt.legend()



print("P:", f.pdf(F, dfn, dfd))

dov_int = df_new.mean() + 1.96*(np.std(df_new)/df_new.count()**0.5)
print(dov_int)

import matplotlib.pyplot as plt

means = df_new.mean()
stds = df_new.std(ddof=1)
ns = df_new.count()
z = 1.96

ci_lower = means - z * (stds / np.sqrt(ns))
ci_upper = means + z * (stds / np.sqrt(ns))

ci_df = pd.DataFrame({
    'mean': means,
    'ci_lower': ci_lower,
    'ci_upper': ci_upper
})

print(ci_df)

# Построение боксплота
plt.figure(figsize=(8, 5))
plt.boxplot([df_new[col].dropna() for col in df_new.columns], labels=df_new.columns)
plt.title('Boxplot по группам')
plt.ylabel('expr')
plt.xlabel('Группа терапии')
plt.grid(True)
plt.show()